repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt # форматирование
      - id: go-mod-tidy # проверка чистоты go.mod


  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.3
    hooks:
      - id: golangci-lint
        args: ['--timeout=3m']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]