repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt        # форматирование
      - id: go-imports    # оптимизация импортов
      - id: go-vet        # статический анализ
      - id: go-mod-tidy   # проверка чистоты go.mod
